### ISSUE TITLE
SiamFC with pretrained would run slower and slower

### ISSUE THREAD

**Issue by MzeroMiko** [huuuuusy/videocube-toolkit#2]
ISSUE and CAUSE:
we find that when using SiamFC with pretrained model in this toolkit, the code would get slower and slower (from <1 second to even > 2 minutes per sample). When using SiamFC without pretraining, we did not find this issue. 
Then we find out that is because the SiamFC with pretrained predict a bad center: the center get out of the image and fly far and far way, which makes the function `siamfc.py: TrackerSiamFC._crop_and_resize`  run slower and slower.

SOLUTION:
we just add some code in `siamfc.py: TrackerSiamFC.update` to restrict the center within (-2*height, 2*height) x (-2*width, 2*width) and solve this issue
```python
# return 1-indexed and left-top based bounding box
        box = np.array([
            self.center[1] + 1 - (self.target_sz[1] - 1) / 2,
            self.center[0] + 1 - (self.target_sz[0] - 1) / 2,
            self.target_sz[1], self.target_sz[0]])
        
        # to keep center not that rediculars, which effects self._crop_and_resize
        if abs(self.center[0]) > 2 * height or abs(self.center[1]) > 2 * width:
            print("WARNING: Force reset center. center:", self.center, ", size:", self.target_sz)
            self.center[0] = height if self.center[0] > 0 else 0
            self.center[1] = width if self.center[1] > 0 else 0


        if box[0] < 0 or box[1] < 0 or box[0]+box[2] > width or box[1]+box[3] > height:
            box = np.array([0,0,0,0])
        return box
```

**Comment by huuuuusy** [comment]
Thanks a lot; I have updated the codes based on your suggestion.

**Comment by zugofn** [comment]
> 

Hi!
How about the test FPS after modify the code?
It takes me a few days to test the entire dataset.

**Comment by MzeroMiko** [comment]
in rtx3090, siamfc reaches 123fps in val dataset in my experiments.



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 22, 2022 15:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [huuuuusy/videocube-toolkit] SiamFC with pretrained would runslower and slower (Issue #2)




   
Hi!
 How about the test FPS after modify the code?
 It takes me a few days to test the entire dataset.
