### ISSUE TITLE
Missing data and mismatched video

### ISSUE THREAD

**Issue by ncTimTang** [huuuuusy/videocube-toolkit#6]
Thanks for your impressive work. There should be 129 fiiles in the MGIT-train dataset, but in the Baiduyun Disk: https://pan.baidu.com/s/1meBFShzApC6dZX3d9klm1Q, there are only 101files similar to val and test.

Also, in the MGIT\MGIT-Info\attribute\attribute\description\024.json, there is a sentence related to frame 14295 while only 9622 frames in video024. Similar problems also occur in other video. How can I solve these?

**Comment by huuuuusy** [comment]
Thanks a lot for pointing out our oversights. We have successfully uploaded the pertinent sequence files to both Baidu Yun and OneDrive, and we have also revised the annotation file for sequence 024. Please check the updated version.
