### ISSUE TITLE
Pytracking test on MGIT

### ISSUE THREAD

**Issue by Confetti-lxy** [huuuuusy/videocube-toolkit#7]
Thanks for your impressive work. But I have some doubts about the test of pytracking method on the MGIT dataset. The README only mention result conversion and submission test. Do this mean I need to test on the pytracking frame first? If yes, now the pytracking frame do not include MGIT in their dataset, could you please provide a dataset code on pytracking?  Thanks!

**Comment by Xuchen-Li** [comment]
Hello, You need to test within the pytracking framework and then convert the results for submission on the videocube website. Currently, the pytracking framework does not directly include the MGIT dataset. If you encounter issues while integrating the MGIT dataset into the pytracking framework, we will soon provide a code example for loading and using the MGIT dataset.
Thank you for your attention and support for MGIT dataset.

**Comment by Confetti-lxy** [comment]
Thank you for your reply, and many thanks to you that provide provide a code example for loading and using the MGIT dataset!

**Comment by Confetti-lxy** [comment]
Hello! I would like to ask if the code for loading and using the MGIT dataset can be released in this week？
